# Predecir el trafico usando un regresor extremadamente aleatorio

https://archive.ics.uci.edu/ml/datasets/Dodgers+Loop+Sensor. Este conjunto de datos constade datos que cuentan la cantidad de vehículos que pasan por la carretera durante los juegos de béisbol en el estadio Los Angeles Dodgers.

Martes, 00:00, San Francisco, no, 3
Día de la semana, hora del día, equipo oponente, valor binario que indica si unEl juego de béisbol está actualmente en curso (sí / no), número de vehículos que pasan.


In [52]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, mean_absolute_error
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import ExtraTreesRegressor

In [62]:
input_file = 'traffic_data.txt'
data = []

with open(input_file, 'r') as f:
    for line in f.readlines ():
        items = line[:-1].split(',')
        data.append(items)
        
data = np.array(data)

In [63]:
#Codificando los caracteres no numericos de los datos
label_encoder=[]
X_encoded = np.empty(data.shape)
for i, item in enumerate(data[0]):
    if item.isdigit():
        X_encoded[:,i] = data[:, i]
    else:
        label_encoder.append(preprocessing.LabelEncoder())
        X_encoded[:, i] = label_encoder[-1].fit_transform(data[:, i])
         
        
print(X_encoded)


[[  5.   0.  13.   0.   3.]
 [  5.   1.  13.   0.   8.]
 [  5.   2.  13.   0.  10.]
 ...
 [  4. 285.   0.   0.  11.]
 [  4. 286.   0.   0.  14.]
 [  4. 287.   0.   0.  17.]]


In [64]:
X = X_encoded[:, :-1].astype(int)
y = X_encoded[:, -1].astype(int)

#Training and testing
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=5)

In [65]:
#Construcción de regresor 
params = {'n_estimators':100, 'max_depth': 4, 'random_state':0}
regressor = ExtraTreesRegressor(**params)
regressor.fit(X_train, y_train)

#Probando el rendimiento del regresor 
y_pred = regressor.predict(X_test)
print("Error absoluto medio:", round(mean_absolute_error(y_test, y_pred), 2) )

Error absoluto medio: 7.42


In [67]:
#Probar el regresor con etiquetas de datos de entrada 
#test_datapoint = ['Saturday', '10:20', 'Atlanta', 'no']
#test_datapoint = ['Tuesday','21:25','San Francisco','no']
test_datapoint = ['Wednesday','00:05','San Francisco','no']
test_datapoint_encoded = [-1] * len(test_datapoint)

count = 0

for i, item in enumerate(test_datapoint):
    if item.isdigit():
        test_datapoint_encoded[i] = int(test_datapoint[i])
    else:
        test_datapoint_encoded[i] = int(label_encoder[count].transform( [test_datapoint[i]] ))
        count = count + 1
        
test_datapoint_encoded = np.array(test_datapoint_encoded)
print("Predicción de trafico:", int(regressor.predict( [test_datapoint_encoded])[0] ))


Predicción de trafico: 5
