In [3]:
import numpy as np
from sklearn import preprocessing

In [17]:
#Tecnicas de preprocesamiento de datos
#para aprendizaje supervisado 

input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]])

#binarización de datos: convertimos nuestros datos en valores boolean
#threshold: definimos el valor umbral para la clasificación
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n",  data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [18]:
#Clasificación por eliminación media 
print("\nBefore:")
print("Media = ",input_data.mean(axis=0))
print("Std desviación =", input_data.std(axis=0))


Before:
Media =  [ 3.775 -1.15  -1.3  ]
Std desviación = [3.12039661 6.36651396 4.0620192 ]


In [19]:
#Remover media
data_scaled = preprocessing.scale(input_data)
print("\nAfter:")
print("Mean =", data_scaled.mean(axis=0))
print("Std desviación =", data_scaled.std(axis=0))


After:
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std desviación = [1. 1. 1.]


In [21]:
#Clasifiación por escala
#Se clasifican de tal forma  que el maximo valor sea 1 de cada   fila 
#y los demas sean relativos a este 
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max Scaled data:\n",data_scaled_minmax)


Min max Scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


In [22]:
#Normalización de datos  por tecnica L1 o L2

#L1: Se refiere a las desviaciones mínimas absolutas, funciona asegurándose de que la suma de los valores absolutos sea 1 en cada fila
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
#L2: Se refiere a los minimos cuadrados , funciona asegurandoss que la suma de los minimos cuadrados sea  1
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')

print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

L2 normalized data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]
